# Clean Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Retail_Sales_and_Retail_Use_Business_Registrations.csv')

In [3]:
df

,Active or Inactive Business,Tax Type,Retail Permit Number,Consolidated Number,Name of Business,Address of the Business,State,County Name,Registration County Number,Business Location County Number,Department City Code,City Location of Business,Business Zip Code,NAICS code,Description of type of NAICS code,Date Permit was Issued,Date Permit was Cancelled
0,Active,Retail Sales,157031946,NaN,NORTH LINN FORD INC,1001 FORD LN,IA,Linn,57,57,3.0,CENTER POINT,52213-9304,4411.0,Automobile Dealers,1985-11-01,NaN
1,Active,Retail Sales,182046684,NaN,"TEUFEL HUNDEN ELECTRONICS, TEUFEL HUNDEN ELECT...",102 E KIMBERLY RD STE 1 BOX 147,IA,Scott,82,82,1.0,DAVENPORT,52806-5922,8112.0,Electronic and Precision Equipment Repair and ...,2020-01-01,NaN
2,Inactive,Retail Sales,127004661,NaN,"STEVENSON, APRIL J; TOWN BUSY BODY",30602 ELK CHAPEL RD,IA,Decatur,27,27,1.0,LAMONI,50140-2289,5617.0,Services to Buildings and Dwellings,2014-01-01,2020-03-31
3,Active,Retail Sales,180002351,NaN,"SOBOTKA, GARY L; GLS MFG",2138 220TH ST,IA,Ringgold,80,80,1.0,MOUNT AYR,50854-8955,459110.0,Sporting Goods Retailers,1985-09-15,NaN
4,Active,Retail Sales,114008902,NaN,PIGEASY LLC,31423 JADE AVE,IA,Carroll,14,14,12.0,TEMPLETON,51463-8555,3399.0,Other Miscellaneous Manufacturing,2014-12-01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339062,Active,Retail Sales,307409520,307409420,"GLP-1 COLLECTIVE, GLP-1 ACCESS LLC",6701 CORPORATE DR STE N,IA,Polk,57,77,16.0,JOHNSTON,50131-1659,455219.0,All Other General Merchandise Retailers,2025-07-04,NaN
339063,Active,Retail Sales,306503521,306503521,GLP-1 COLLECTIVE,1515 GLEN ROCK CIR,IA,Linn,57,57,2.0,MARION,52302-8012,813212.0,Voluntary Health Organizations,2025-04-15,NaN
339064,Active,Retail Sales,306503621,306503521,GLP-1 COLLECTIVE,315 E ST STE 202,IA,Black Hawk,57,7,1.0,WATERLOO,50703-0000,813212.0,Voluntary Health Organizations,2025-04-15,NaN
339065,Active,Retail Sales,307105624,307105624,B & BS VARIETY STORE,114 SE LITTLE BEAVER CT,IA,Polk,77,77,8.0,GRIMES,50111-1153,455219.0,All Other General Merchandise Retailers,2024-10-01,NaN
339066,Active,Retail Sales,307105724,307105624,"B & BS VARIETY STORE, MAIN STORE",111 E WASHINGTON ST,IA,Clarke,77,20,1.0,OSCEOLA,50213-1244,455219.0,All Other General Merchandise Retailers,2024-10-01,NaN

In [4]:
df.describe()

,Registration County Number,Business Location County Number,Department City Code,NAICS code
count,339067.000000,339067.000000,230596.000000,272902.000000
mean,38.856141,39.934789,2.982524,291470.020110
std,34.536018,34.398424,3.390237,277746.537531
min,0.000000,0.000000,1.000000,238.000000
25%,0.000000,0.000000,1.000000,5415.000000
50%,33.000000,38.000000,1.000000,315990.000000
75%,77.000000,77.000000,3.000000,459510.000000
max,99.000000,99.000000,21.000000,928120.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339067 entries, 0 to 339066
Data columns (total 17 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Active or Inactive Business        339067 non-null  object
 1   Tax Type                           339067 non-null  object
 2   Retail Permit Number               339067 non-null  object
 3   Consolidated Number                181982 non-null  object
 4   Name of Business                   339067 non-null  object
 5   Address of the Business            339057 non-null  object
 6   State                              338065 non-null  object
 7   County Name                        230596 non-null  object
 8   Registration County Number         339067 non-null  int64
 9   Business Location County Number    339067 non-null  int64
 10  Department City Code               230596 non-null  float64
 11  City Location of Business          339023 non-null  object
 12  Business Zip Code                  338297 non-null  object
 13  NAICS code                         272902 non-null  float64
 14  Description of type of NAICS code  272902 non-null  object
 15  Date Permit was Issued             339067 non-null  object
 16  Date Permit was Cancelled          113066 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 44.0+ MB

In [33]:
missing_summary = df.isnull().sum().sort_values(ascending=False)

In [34]:
missing_summary

Active or Inactive Business    0
Tax Type                       0
Name of Business               0
State                          0
County Name                    0
City Location of Business      0
Date Permit was Issued         0
dtype: int64

In [11]:
df.drop(columns=['Date Permit was Cancelled','Consolidated Number','Department City Code','Department City Code','Description of type of NAICS code','NAICS code','Business Zip Code','Address of the Business','Business Location County Number','Retail Permit Number','Registration County Number'],inplace=True)

In [12]:
df

,Active or Inactive Business,Tax Type,Name of Business,State,County Name,City Location of Business,Date Permit was Issued
0,Active,Retail Sales,NORTH LINN FORD INC,IA,Linn,CENTER POINT,1985-11-01
1,Active,Retail Sales,"TEUFEL HUNDEN ELECTRONICS, TEUFEL HUNDEN ELECT...",IA,Scott,DAVENPORT,2020-01-01
2,Inactive,Retail Sales,"STEVENSON, APRIL J; TOWN BUSY BODY",IA,Decatur,LAMONI,2014-01-01
3,Active,Retail Sales,"SOBOTKA, GARY L; GLS MFG",IA,Ringgold,MOUNT AYR,1985-09-15
4,Active,Retail Sales,PIGEASY LLC,IA,Carroll,TEMPLETON,2014-12-01
...,...,...,...,...,...,...,...
339062,Active,Retail Sales,"GLP-1 COLLECTIVE, GLP-1 ACCESS LLC",IA,Polk,JOHNSTON,2025-07-04
339063,Active,Retail Sales,GLP-1 COLLECTIVE,IA,Linn,MARION,2025-04-15
339064,Active,Retail Sales,GLP-1 COLLECTIVE,IA,Black Hawk,WATERLOO,2025-04-15
339065,Active,Retail Sales,B & BS VARIETY STORE,IA,Polk,GRIMES,2024-10-01
339066,Active,Retail Sales,"B & BS VARIETY STORE, MAIN STORE",IA,Clarke,OSCEOLA,2024-10-01

In [20]:
city_to_county = (
    df[df['County Name'] != 'Unknown'][['City Location of Business', 'County Name']]
    .dropna()
    .drop_duplicates()
    .set_index('City Location of Business')['County Name']
    .to_dict()
)

In [21]:
df['County Name'] = df.apply(
    lambda row: city_to_county.get(row['City Location of Business'], row['County Name']),
    axis=1
)

In [25]:
print("Remaining 'Unknown' County Names:", (df['County Name'] == 'Unknown').sum())

Remaining 'Unknown' County Names: 0

In [31]:
df.loc[:, 'County Name'] = df['County Name'].fillna('Unknown')
df.loc[:, 'State'] = df['State'].fillna('IA')
df = df[df['City Location of Business'].notnull()]

In [35]:
df.to_csv("Cleaned_Business_Registrations.csv", index=False)

#Geographic Distribution

In [37]:
top_counties = df['County Name'].value_counts().head(10)

In [38]:
top_counties

County Name
Unknown       89201
Warren        22950
Linn          15518
Polk          14002
Scott         10573
Story          9130
Johnson        8941
Black Hawk     8808
Dallas         8711
Plymouth       7601
Name: count, dtype: int64

In [39]:
top_cities = df['City Location of Business'].value_counts().head(10)

In [40]:
top_cities

City Location of Business
DES MOINES         15050
CEDAR RAPIDS        9902
AMES                6614
DAVENPORT           6492
WEST DES MOINES     5576
SIOUX CITY          5509
DUBUQUE             4876
ANKENY              4586
WATERLOO            4535
IOWA CITY           4348
Name: count, dtype: int64